### ISSUE TITLE
Not returning any values for oas_report()

### ISSUE THREAD

**Issue by ericbrownaustin** [ReportMort/roas#2]
I am trying to pull a page@position report.  My credentials seem to be working correctly and I am able correctly pull the site list report, but any time I try to use the oas_report() function, no data is returned.

`oas_report(my_credentials, 
                      report_type = 'campaign group delivery', 
                      report_name = 'page@position delivery information', 
                      id='mysite',
                      start_date = '2016-12-01',
                      end_date = '2016-12-31')`

**Comment by StevenMMortimer** [comment]
@ericbrownaustin I think the `id` argument must be the id of a valid campaign group, not a site since the report is a summary at the level of campaign groups. Would you mind trying that?

**Comment by ericbrownaustin** [comment]
That works.  Is there a way to pull all campaign ids for a particular date range?  I have gone through the documentation and I haven't been able to.

**Comment by StevenMMortimer** [comment]
`oas_list()` with search criteria. Here is an example of pulling all the campaigns with an end date on or after Jan 1st, 2017. 

```
list_campaigns <- oas_list(credentials=my_credentials, request_type='Campaign', 
                           search_criteria=list(newXMLNode("EndDate", 
                                                           attrs = c(condition = "GE"), 
                                                           '2017-01-01')))
```

If you want to find campaigns based on delivery, then use a Campaign Delivery report for a site.
